image: proboci/ubuntu:18.04-php7.3
steps:
  - name: Download Wordpress latest release.
    plugin: Script
    script: |
      wget -c https://wordpress.org/latest.tar.gz -O - | tar -xz -C /src
  - name: Update wp-cli.
    plugin: Script
    script: |
      wp cli update --allow-root --yes
  - name: Wordpress site setup with Varnish enabled...
    plugin: WordPressApp
    subDirectory: 'wordpress'
    devDomain: 'http://example.com'
    devHome: 'http://example.com/'
    flushCaches: true
    varnish:
      enable: true
  - name: Install WordPress site.
    plugin: Script
    script: |
      cd /src/wordpress
      wp core install --url=$BUILD_DOMAIN --title=Example --admin_user=supervisor --admin_password=strongpassword --admin_email=info@example.com --allow-root
