image: proboci/ubuntu:18.04-php7.3
steps:
  - name: Download Drupal 8 Core latest release.
    plugin: Script
    script: |
      composer create-project drupal-composer/drupal-project:8.x-dev /tmp/src --no-interaction
      cp -Rf /tmp/src/* /src
      cd /src
      composer require drupal/devel drush/drush cweagans/composer-patches
      composer install
  - name: Install Drupal 8 standard profile with varnish enabled.
    plugin: Drupal
    clearCaches: true
    subDirectory: web
    drupalVersion: 8
    runInstall: standard
    varnish:
      enable: true
