image: proboci/ubuntu:18.04-php7.3
steps:
  - name: Download Drupal 8 Core latest release.
    plugin: Script
    script: |
      composer create-project drupal-composer/drupal-project:8.x-dev /tmp/src --no-interaction
      cp -Rf /tmp/src/* /src
      cd /src
      composer require drupal/devel drush/drush cweagans/composer-patches
      composer install
  - name: Drupal 8 site install.
    plugin: Drupal
    clearCaches: false
    subDirectory: web
    drupalVersion: 8
  - name: Install Drupal 8 site.
    plugin: Script
    script: |
      vendor/drush/drush/drush site-install -y --root=/var/www/html standard --db-url='mysqli://root:strongpassword@localhost/drupal'
  - name: Generate login link.
    plugin: Script
    script: |
      vendor/drush/drush/drush uli
